[package]
name = "postgres_user_crud"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pad = "0.1.6"
postgres = { version = "0.19.8", features = ["array-impls"] }
thiserror = "1.0.63"
